annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Remove integration tests"
    - kind: fixed
      description: "Add aws-enabled property to secondary-storage config"
    - kind: fixed
      description: "Use internal cluster url for connectors in console release info"
    - kind: fixed
      description: "#5874 remove prerelease annotation"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  camunda.io/component-image-versions: |
    camunda: 8.9.1
    managementIdentity: 8.9.1
    optimize: 8.9.1
    webModeler: 8.9.1
    connectors: 8.9.1
    console: 8.9.26
  camunda.io/helmCLIVersion: 3.20.2
  camunda.io/imageOverrides: |+
    connectors: 8.9.1
    console: 8.9.26
    optimize: 8.9.1
    orchestration: 8.9.1
    modeler: 8.9.1
    identity: 8.9.1

apiVersion: v2
appVersion: 8.9.x
dependencies:
- alias: identityKeycloak
  condition: identityKeycloak.enabled
  name: keycloak
  repository: file://../keycloak-24
  version: 24.x.x
#- alias: identityPostgresql
#  condition: identityPostgresql.enabled
#  name: postgresql
#  repository: file://../identity-postgresql-16
#  version: 16.x.x
#- alias: webModelerPostgresql
#  condition: webModelerPostgresql.enabled
#  name: web-modeler-postgresql
#  repository: file://../web-modeler-postgresql-15
#  version: 15.x.x
#- condition: elasticsearch.enabled
#  name: elasticsearch
#  repository: file://../elasticsearch-21
#  version: 21.6.3
- name: common
  repository: file://../common-2
  version: 2.x.x
description: 'Camunda 8 Self-Managed Helm charts. Camunda''s process automation platform
  allows developers to design, automate and improve processes. '
home: https://docs.camunda.io/docs/self-managed/about-self-managed/
icon: https://helm.camunda.io/imgs/camunda.svg
keywords:
- automation
- business-rules
- bpm
- bpmn
- camunda-platform
- decision-engine
- dmn
- modeling
- orchestration
- process-automation
- process-engine
- process-orchestration
- workflow
- workflow-engine
maintainers:
- email: ahmed.abouzaid@camunda.com
  name: aabouzaid
- email: daniel.rodriguez@camunda.com
  name: drodriguez-305
- email: hamza.masood@camunda.com
  name: hamza-m-masood
- email: jesse.simpson@camunda.com
  name: jessesimpson36
name: camunda-platform
sources:
- https://github.com/camunda/camunda-platform-helm
type: application
version: 14.0.1
