apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/instance: "camunda-keycloak"
type: Opaque
data: {}